server:
  port: 8080
  servlet:
    context-path: /api/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop